version: "3.8"

services:
    db:
        build: db/
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
           MYSQL_ROOT_PASSWORD: admin
        volumes:
           - data-volume:/var/lib/mysql
volumes:
    data-volume:
